// ============================================================
// Generated by CFGen v2
// File       : ${filename}
// Absolute   : ${abspath}
// Directory  : ${dir}
// Generated  : ${date} ${time}
// ISO Time   : ${iso_date}
// Unix Time  : ${unix_time}
//
// Use this -p"<MyApp,Core,TestClass,FooBarBaz,Object,true, v2.0.0 >"
// ============================================================

#pragma once

// ================= Runtime Variables =================
@register ProjectName
@register ModuleName
@register ClassName
@register AuthorName
@register BaseClass
@register FeatureFlag
@register VersionString

// ================= Include Guard =====================
#ifndef ${upper:${snake:${ProjectName}}}_${upper:${snake:${ClassName}}}_H
#define ${upper:${snake:${ProjectName}}}_${upper:${snake:${ClassName}}}_H

#include <string>
#include <cstdint>
#include <utility>

// ================= Namespace =========================
namespace ${snake:${ProjectName}}::${snake:${ModuleName}}
{

// ====================================================
// Class: ${ClassName}
// Author: ${title:${AuthorName}}
// Created: ${weekday}, ${month} ${year}
// Version: ${trim:${VersionString}}
// ====================================================
class ${pascal:${ClassName}} : public ${pascal:${BaseClass}}
{
public:
    // ---------------- Constructors ----------------
    ${pascal:${ClassName}}();
    explicit ${pascal:${ClassName}}(std::string name);

    // ---------------- Rule of 5 -------------------
    ${pascal:${ClassName}}(const ${pascal:${ClassName}}&) = default;
    ${pascal:${ClassName}}(${pascal:${ClassName}}&&) noexcept = default;
    ${pascal:${ClassName}}& operator=(const ${pascal:${ClassName}}&) = default;
    ${pascal:${ClassName}}& operator=(${pascal:${ClassName}}&&) noexcept = default;
    virtual ~${pascal:${ClassName}}();

    // ---------------- Accessors -------------------
    const std::string& getName() const noexcept;
    void setName(const std::string& name);

    // ---------------- State -----------------------
    bool isEnabled() const noexcept;
    void setEnabled(bool enabled);

    // ---------------- Utilities -------------------
    static std::string classSlug();
    static std::string reversedName();

    // ---------------- Debug -----------------------
    std::string toString() const;

private:
    std::string m_name;
    bool        m_enabled { ${lower:${FeatureFlag}} };
};

// ================= Inline Implementations =================

inline ${pascal:${ClassName}}::${pascal:${ClassName}}()
    : m_name("${camel:${ClassName}}"), m_enabled(${lower:${FeatureFlag}})
{}

inline ${pascal:${ClassName}}::${pascal:${ClassName}}(std::string name)
    : m_name(std::move(name)), m_enabled(${lower:${FeatureFlag}})
{}

inline ${pascal:${ClassName}}::~${pascal:${ClassName}}() = default;

inline const std::string&
${pascal:${ClassName}}::getName() const noexcept
{
    return m_name;
}


inline bool
${pascal:${ClassName}}::isEnabled() const noexcept
{
    return m_enabled;
}


inline std::string
${pascal:${ClassName}}::classSlug()
{
    return "${slug:${ClassName}}";
}

inline std::string
${pascal:${ClassName}}::reversedName()
{
    return "${reverse:${ClassName}}";
}

inline std::string
${pascal:${ClassName}}::toString() const
{
    return std::string{
        "Class=${pascal:${ClassName}}, "
        "Project=${upper:${ProjectName}}, "
        "Module=${lower:${ModuleName}}, "
        "File=${stem}.${ext}"
    };
}

} // namespace ${snake:${ProjectName}}::${snake:${ModuleName}}

#endif // ${upper:${snake:${ProjectName}}}_${upper:${snake:${ClassName}}}_H
