// ============================================================
// Generated by CFGen v2
// File       : cpp_ver2_header_full_test.h
// Absolute   : C:\Amash\Programs\CFGen\Tests\Outputs\cpp_ver2_header_full_test.h
// Directory  : .\Tests\Outputs
// Generated  : 2026-02-25 16:46:42
// ISO Time   : 2026-02-25T16:46:42
// Unix Time  : 1772018202
//
// Use this -"p<MyApp,Core,TestClass,FooBarBaz,Object,true, v2.0.0>"
// ============================================================

#pragma once

// ================= Runtime Variables =================

// ================= Include Guard =====================
#ifndef MY_APP_TEST_CLASS_H
#define MY_APP_TEST_CLASS_H

#include <string>
#include <cstdint>
#include <utility>

// ================= Namespace =========================
namespace my_app::core
{

// ====================================================
// Class: TestClass
// Author: Amash
// Created: Wednesday, February 2026
// Version: v2.0.0
// ====================================================
class Testclass : public Object
{
public:
    // ---------------- Constructors ----------------
    Testclass();
    explicit Testclass(std::string name);

    // ---------------- Rule of 5 -------------------
    Testclass(const Testclass&) = default;
    Testclass(Testclass&&) noexcept = default;
    Testclass& operator=(const Testclass&) = default;
    Testclass& operator=(Testclass&&) noexcept = default;
    virtual ~Testclass();

    // ---------------- Accessors -------------------
    const std::string& getName() const noexcept;
    void setName(const std::string& name);

    // ---------------- State -----------------------
    bool isEnabled() const noexcept;
    void setEnabled(bool enabled);

    // ---------------- Utilities -------------------
    static std::string classSlug();
    static std::string reversedName();

    // ---------------- Debug -----------------------
    std::string toString() const;

private:
    std::string m_name;
    bool        m_enabled { true };
};

// ================= Inline Implementations =================

inline Testclass::Testclass()
    : m_name("testclass"), m_enabled(true)
{}

inline Testclass::Testclass(std::string name)
    : m_name(std::move(name)), m_enabled(true)
{}

inline Testclass::~Testclass() = default;

inline const std::string&
Testclass::getName() const noexcept
{
    return m_name;
}


inline bool
Testclass::isEnabled() const noexcept
{
    return m_enabled;
}


inline std::string
Testclass::classSlug()
{
    return "testclass";
}

inline std::string
Testclass::reversedName()
{
    return "ssalCtseT";
}

inline std::string
Testclass::toString() const
{
    return std::string{
        "Class=Testclass, "
        "Project=MYAPP, "
        "Module=core, "
        "File=cpp_ver2_header_full_test..h"
    };
}

} // namespace my_app::core

#endif // MY_APP_TEST_CLASS_H
