#pragma once

char* GetNoArgumentsErrorString();
char* GetInsufficientArgumentsForGenErrorString();
char* GetInsufficientArgumentsForRegMacErrorString();
char* GetInsufficientArgumentsForRegTempErrorString();
char* GetInsufficientArgumentsForDelTempErrorString();
char* GetFileDoesNotExitForTempGenErrorString();
char* GetTempRegFileCannotBeCreatedErrorString();
char* GetTempAlrExistsErrorString();
char* GetTempNotFoundForDeletion();
char* GetCannotOpenProvidedFileErrorString();
char* GetConnotCopyScriptFileErrorString();
char* GetTemplateNotfoundErrorString();
char* GetTemplateFileCannotBeWritten();
char* GetCannotDeleteScriptFile();
char* GetStringHelp();
char* GetStringRegTempSuccessfull();
char* GetStringDelTempSuccessfull();